services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d main_db"]
      interval: 5s

  web:
    build: .
    # command: /app/scripts/entrypoint.sh
    volumes:
      - .:/app
      - ./static_files:/app/staticfiles
    expose:
      - "8000" # Only exposed internally to Nginx
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/main_db
      - SECRET_KEY=prod-secret
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
